version: "3.3"

services:

  kibana:
    image: docker.elastic.co/kibana/kibana:6.2.4
    hostname: "{{.Node.Hostname}}-kibana"
    ports:
      - 5601:5601
    environment:
      - ELASTICSEARCH_URL=http://elasticsearch:9200
#      - ELASTICSEARCH_USERNAME=elastic
#      - ELASTICSEARCH_PASSWORD=changeme
      - SERVER_NAME="{{.Node.Hostname}}-kibana"
      - xpack.monitoring.elasticsearch.url='http://elasticsearch:9200'
      - xpack.security.enabled=false
      - xpack.monitoring.enabled=true
      - xpack.monitoring.ui.container.elasticsearch.enabled=true
      - xpack.apm.ui.enabled=false
      - xpack.graph.enabled=false
      - xpack.ml.enabled=false
    networks:
      - network-logging
    volumes:
      - kibana:/usr/share/kibana/data
    deploy:
      labels:
        - com.df.notify=true
        - com.df.distribute=true
        - com.df.servicePath=/
        - com.df.port=5601
        - com.df.srcPort=5601
        
networks:
    network-logging:
      external: true

volumes:
  kibana: